---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: k8s-vault-config
  namespace: flux-system
spec:
  enableInventory: true
  interval: 5m
  approvePlan: auto
  path: ./base/terraform/k8s-vault-config
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: azure-config
  namespace: flux-system
  annotations:
    metadata.weave.works/description: This is a sample set of objects for Azure such as role bindings and cloud functions.
spec:
  enableInventory: true
  interval: 5m
  approvePlan: auto
  path: ./base/terraform/azure-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: azure-tf-credentials
